# external file paths relative from $HOME
debt: Shared/database/tracker/finances/debt.csv
periodic_debt: Shared/database/tracker/finances/periodic_debt.yml
expenses: Shared/database/tracker/finances/expenses.csv
keepass: Shared/database/authentification/kiesel_markus_pw.kdbx
food: Shared/database/tracker/health/food.csv

